//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridge.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class itemTbl
    {
        [Key]
        [Required]
        public int itemID { get; set; }
        [Required]
        [Display(Name = "Item Name")]
        public string itemName { get; set; }
        [Required]
        [Display(Name = "Item Desc")]
        public string itemDescription { get; set; }
        [Required]
        [Display(Name = "Item Price")]
        public int itemPrice { get; set; }
        [Display(Name = "Item Image")]
        public byte[] itemImage { get; set; }
    }
}
